### PR TITLE
use relative link so it works independently of where it's hosted

### PR DESCRIPTION
**Pull request by et**
@humeansacrifice - review this please.

### CODE REVIEW

**Comment by humeansacrifice** [comment]
@et I don't know how to test it, but looks like the other relative link has been there for a while with no issues so (shrug), looks fine.

**Comment by et** [comment]
@humeansacrifice - did you get mkdocs to run locally?
If so, you should see the link showing up as `http://127.0.0.1:8000/kb/api-version-3/object-field-references#visitor-activity/kb/api-version-3/object-field-references#visitor-activity-types` instead of `http://developer.pardot.com/kb/api-version-3/object-field-references#visitor-activity/kb/api-version-3/object-field-references#visitor-activity-types`
The benefit of doing it this way is that it doesn't matter where we host it (developer.pardot.com, 127.0.0.1:8000, etc), it'll work since we've removed the hardcoded dependency.

**Comment by humeansacrifice** [comment]
@et Yep, running locally. When I hover the link is http://127.0.0.1:8000/kb/api-version-3/object-field-references#visitor-activity/kb/api-version-3/object-field-references#visitor-activity-types.

I get a 404 error if I click it though -- is that supposed to happen?

**Comment by humeansacrifice** [comment]
Relative links working now. We're good to go here!

**Pull request merged**
