### PR TITLE
Remove the "kb/api-version-3/" prefix from relative links

### LINKED ISSUE #55: Links to knowledge base are broken
Links to other knowledge-base pages include the "kb/api-version-3" prefix twice and return a 404.

Example: the links in "Also see Campaign in Object Field References" at the top of http://developer.pardot.com/kb/api-version-3/campaigns/

### PR DESCRIPTION
**Pull request by RyanLB**
Fixes #55. Removes the "kb/api-version-3" prefix from relative links any time it appears.

### CODE REVIEW

**Comment by humeansacrifice** [comment]
@et this looks good to me. Can we merge?

**Comment by bmsteele** [comment]
i like #YOLO

**Comment by et** [comment]
@humeansacrifice says she was having problems with these links locally...we should revert this unless someone can confirm this works properly

**Comment by bmsteele** [comment]
@et yep reverted for now. When you test locally, the change is good if you manually append a trailing slash (so locally kb/api-version-3/object-field-references doesn't work but kb/api-version-3/object-field-references/ does —— but this should be handled nicely with a 301 redirect on our web server anyway).

All that being said... I'm missing something here. Not sure why these links stopped working in the first place. I had a dated local copy and didn't really see any differences.

**Comment by et** [comment]
I actually just tried this locally and it seemed to work fine. @humeansacrifice can you provide some details as to what your issue was?

**Comment by humeansacrifice** [comment]
@et I get 404s for the links that were previously broken.

**Comment by et** [comment]
Thanks @RyanLB! I believe we had some people on different versions of `mkdocs` but those are fixed.
Your changes are now live.
Much :heart:

**Pull request merged**
